import dev.monosoul.jooq.RecommendedVersions

// infra-persistence: Postgres adapter. Allowed: application + jOOQ + Flyway + Postgres driver.
// NO Spring in this module (the Spring Flyway/DataSource auto-configuration lives in :app).
//
// jOOQ classes are generated by the jooq-docker plugin: it spins up a throwaway Postgres 16
// container, runs the Flyway migrations from src/main/resources/db/migration against it, and
// generates jOOQ code from the migrated schema. This requires Docker at build time but NO
// pre-existing/running database — the most robust option for a clean checkout.
plugins {
    id("mcplatform.java-conventions")
    alias(libs.plugins.jooq.docker)
}

dependencies {
    api(project(":application"))

    // Runtime jOOQ + Flyway + driver. Marked `api` so :app gets them transitively for
    // Spring Boot's Flyway/DataSource auto-configuration.
    api(libs.jooq)
    api(libs.flyway.core)
    api(libs.flyway.postgresql)
    api(libs.postgresql)

    // Codegen classpath: the plugin bundles its own jOOQ codegen (3.19.x, same minor as the
    // runtime jOOQ above), so we only add the JDBC driver and the Postgres Flyway module for the
    // throwaway codegen database. Do NOT add jooq-codegen here — a second codegen version on this
    // classpath makes the config writer and the bundled XSD validator disagree (SAX warnings).
    jooqCodegen(libs.postgresql)
    jooqCodegen("org.flywaydb:flyway-database-postgresql:${RecommendedVersions.FLYWAY_VERSION}")

    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.assertj.core)
    testImplementation(libs.testcontainers.postgresql)
    testImplementation(libs.testcontainers.junit)
    testRuntimeOnly(libs.junit.platform.launcher)
}

tasks {
    generateJooqClasses {
        schemas.set(listOf("public"))
        basePackageName.set("com.mcplatform.persistence.jooq")
        // migrationLocations defaults to src/main/resources/db/migration.
        includeFlywayTable.set(false)

        withContainer {
            image {
                name = "postgres:16-alpine"
            }
        }
    }
}
